### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by 66Hamidreza** [onionj/x-ui_bot#1]
سلام 
مرسی از کدی که نوشتی لطفا بگو با کدوم پنل بیشتر هماهنگ هست ؟
من رو پنل Franz اجرا کردم استارت هم میشه ولی نه با Email نه با UUID کار میکنه

**Comment by onionj** [comment]
سلام من خودم رو حساب این پنل نوشتمش:
https://github.com/HexaSoftwareTech/x-ui
اونم البته رو حالت Inbound Multi User.

اینکه حالت های دیگه رو پشتیبانی کنه باید اضافه کنم.
